color0 #131314
color1 #ffb4ab
color2 #b8c9d4
color3 #c2c7cc
color4 #d3c1d4
color5 #b8c9d4
color6 #c2c7cc
color7 #e4e2e2
color8 #8d9195
color9 #ffb4ab
color10 #b8c9d4
color11 #c2c7cc
color12 #d3c1d4
color13 #b8c9d4
color14 #c2c7cc
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c3c7cb
selection_background  #43474b
active_border_color   #b8c9d4
inactive_border_color #43474b
url_color             #b8c9d4

active_tab_foreground   #23323b
active_tab_background   #b8c9d4
inactive_tab_foreground #c3c7cb
inactive_tab_background #43474b
cursor_trail_color      #c3c7cb
