#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:


# erec-once = ~./config/waybar/scripts/launch.sh

#exec-once = awww-daemon
# exec-once = waybar
exec-once = qs -c noctalia-shell

exec-once = [workspace 2 silent] zen-browser
