###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = qs -c noctalia-shell ipc call launcher toggle
$sessionMenu = qs -c noctalia-shell ipc call sessionMenu toggle

